markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

title:          'Școala Generală "Alice Voinescu"'
description:    'Școala Generală "Alice Voinescu" - Bd. Tudor Vladimirescu, nr. 71 A, cod postal 220016, Drobeta-Turnu-Severin, Mehedinți'
url:            'http://scoala2dts.scand.ro'

defaultsocialimage: 'http://scoala2dts.scand.ro/assets/images/og_social.png'
